---
- name: cronjob for restarting {{ chain }} service
  cron:
    name: "restart {{ chain }}-{{ hostvars[inventory_hostname].name }}"
    minute: "{{ polkadot_restart_minute }}"
    hour: "{{ polkadot_restart_hour }}"
    day: "{{ polkadot_restart_day }}"
    month: "{{ polkadot_restart_month }}"
    weekday: "{{ polkadot_restart_weekday }}"
    job: "/bin/systemctl restart {{ chain }}-{{ hostvars[inventory_hostname].name }}.service"
  when: "polkadot_restart_enabled|default(false)|bool"

#- name: register public ip
#  uri:
#    url: https://api.ipify.org?format=json
#  register: public_ip

- name: create {{ chain }} service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/{{ chain }}-{{ hostvars[inventory_hostname].name }}.service
    owner: root
    group: root
    mode: 0600

- name: enable {{ chain }} service
  systemd:
    name: "{{ chain }}-{{ hostvars[inventory_hostname].name }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
