---
# defaults file for polkadot-validator
proxy_port: 80
p2p_port: 30333
chain: "kusama"
polkadot_network_id: "ksmcc3"
subkey_binary_url: 'https://github.com/w3f/substrate/releases/download/e0f3fa/subkey'
subkey_binary_checksum: 'sha256:f74a06442e76c3bb97d27a168b9710ef062ae5640ad82e7d42b8fb613f8be9d9'
build_dir: '/tmp'
in_peers: 200
out_peers: 200
bootnodes:
  - '/ip4/172.25.251.231/tcp/30333/p2p/12D3KooWJGby5TBhQdmv6dbbfHzDXP366nt1noxuK8r8Fhu9abs9'
  - '/ip4/172.25.251.231/tcp/30334/p2p/12D3KooWSP5h5fS5doEXvn7wcWMDA3XpsYaHgD6WqKeooUQKN9nc'
  - '/ip4/172.25.251.231/tcp/30335/p2p/12D3KooWHoiCQerSzMcsMXtnQi3BFXGQF5qNCkryUZVHJap7a6y4'
  - '/ip4/135.181.132.156/tcp/30339/p2p/12D3KooWAezF6BBTAHjPoFjKgwA2vo1rxLCfovuV12foUepDDG6a'
  - '/ip4/46.4.4.36/tcp/30333/p2p/12D3KooWCNVHhq7CghsvWRCxhppssoRKeibRMQmZAzuWfXoKk3Le'
  - '/ip4/13.212.114.222/tcp/30333/p2p/12D3KooWFQ1fhhCDhCc6cYrmC6JiEDyRhKv3ytvJ6z9GqrffmhPk'
