- name: get command output
  shell: |
    set -o pipefail
    journalctl -u {{ chain }}-{{ hostvars[inventory_hostname].name }} --no-pager > /root/polkadot.log
    tail -n 10000 /root/polkadot.log
#    tail -n 10000 /root/polkadot.log | grep "Waiting to import block"
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    msg: "{{ command_output.stdout_lines }}"

- name: remove log
  file:
    path: /root/polkadot.log
    state: absent
