- name: backup keystore
  copy:
    src: "{{ polkadot_basepath }}/{{ chain }}/{{ hostvars[inventory_hostname].name }}/chains/{{ polkadot_network_id }}/keystore"
    dest: /home/polkadot/keystore
    remote_src: yes
